<?php

/*
 * Centre d'aide intégré : guides pas à pas, consultables par recherche.
 * - fonction : fonction de formule nécessaire (sinon la fiche signale qu'elle est dans une formule supérieure) ;
 * - permission : droit nécessaire pour ouvrir l'écran lié (la fiche reste lisible par tous) ;
 * - lien : route de l'écran concerné.
 */
return [
    'rubriques' => [
        'demarrer' => ['Bien démarrer', 'rocket-takeoff'],
        'caisse' => ['Caisse et ventes', 'cart'],
        'stock' => ['Stock et achats', 'box-seam'],
        'clients' => ['Clients et crédits', 'people'],
        'argent' => ['Argent et comptabilité', 'wallet2'],
        'equipe' => ['Équipe et sécurité', 'shield-check'],
        'vente_en_ligne' => ['Vente en ligne', 'shop-window'],
    ],

    'guides' => [
        'premiers-pas' => ['rubrique' => 'demarrer', 'titre' => 'Mettre la boutique en route en 10 minutes',
            'mots' => 'installation démarrage début configuration logo',
            'resume' => 'Les réglages à faire une seule fois avant la première vente.',
            'etapes' => [
                'Paramètres : nom, téléphone, adresse, NIF / RCCM et pied de facture. Ils sont imprimés sur chaque reçu.',
                'Ajoutez votre logo et votre couleur : ils apparaissent sur l\'écran, les reçus et les factures.',
                'Créez vos catégories, puis vos produits (ou importez-les depuis Excel).',
                'Saisissez le stock de départ de chaque produit (ou faites un premier inventaire).',
                'Créez un compte par vendeur : chacun a son code et sa caisse.',
            ],
            'lien' => 'parametres.edit', 'permission' => 'parametres.gerer'],

        'ajouter-produit' => ['rubrique' => 'demarrer', 'titre' => 'Ajouter un produit (prix, gros, code-barres)',
            'mots' => 'article produit prix achat vente gros carton code barre scanner',
            'resume' => 'Fiche produit complète : prix de détail et de gros, conditionnement, seuil d\'alerte.',
            'etapes' => [
                'Produits → Nouveau produit.',
                'Indiquez le prix d\'achat et le prix de vente : la marge est calculée tout de suite.',
                'Vente en gros : prix de gros et quantité minimale ; le prix change seul à la caisse.',
                'Conditionnement (carton de 24, sac de 50 kg…) : on vend alors à l\'unité ou au carton.',
                'Scannez le code-barres du fabricant dans le champ prévu : la caisse retrouvera le produit au scan.',
                'Seuil d\'alerte : sous cette quantité, le produit passe « À commander ».',
            ],
            'lien' => 'produits.create', 'permission' => 'produits.gerer'],

        'import-excel' => ['rubrique' => 'demarrer', 'titre' => 'Importer tout le catalogue depuis Excel',
            'mots' => 'excel import fichier modèle windev csv catalogue',
            'resume' => 'Téléchargez le modèle, remplissez-le, importez : produits, prix et stock en une fois.',
            'etapes' => [
                'Produits → Importer → Télécharger le modèle.',
                'Une ligne par produit ; gardez les titres de colonnes.',
                'Importez le fichier : les erreurs sont signalées ligne par ligne, rien n\'est enregistré à moitié.',
            ],
            'lien' => 'produits.import', 'fonction' => 'import_catalogue', 'permission' => 'produits.gerer'],

        'faire-une-vente' => ['rubrique' => 'caisse', 'titre' => 'Encaisser une vente',
            'mots' => 'vente caisse encaisser ticket reçu scanner caméra téléphone code barre espèces orange money momo paiement',
            'resume' => 'De la recherche du produit à l\'impression du reçu.',
            'etapes' => [
                'Nouvelle vente : scannez ou tapez le nom du produit, la quantité s\'ajuste avec + et −.',
                'Sans lecteur de codes-barres : sur téléphone, le bouton caméra à côté de la recherche scanne les articles les uns après les autres.',
                'Choisissez le client si besoin (obligatoire pour une vente à crédit).',
                'Mode de paiement : espèces, Orange Money, MTN MoMo, carte, ou plusieurs à la fois (paiement fractionné).',
                'En espèces, saisissez le montant reçu : la monnaie à rendre s\'affiche.',
                'Valider : le stock baisse, le reçu est prêt à imprimer ou à envoyer par WhatsApp.',
            ],
            'lien' => 'ventes.create', 'permission' => 'ventes.creer'],

        'mise-en-attente' => ['rubrique' => 'caisse', 'titre' => 'Mettre un ticket en attente',
            'mots' => 'attente pause client oublie reprendre ticket suspendu',
            'resume' => 'Un client est parti chercher de l\'argent ? Gardez son panier et servez le suivant.',
            'etapes' => [
                'À la caisse, bouton « Mettre en attente ».',
                'Le ticket est gardé avec son nom ; servez le client suivant.',
                'Reprenez-le depuis la liste des tickets en attente quand le client revient.',
            ],
            'lien' => 'ventes.create', 'permission' => 'ventes.creer'],

        'proforma' => ['rubrique' => 'caisse', 'titre' => 'Faire un devis ou une facture proforma',
            'mots' => 'devis proforma facture proforma offre prix garanti validité',
            'resume' => 'Aucun stock ne bouge ; les prix sont garantis jusqu\'à la date de validité.',
            'etapes' => [
                'À la caisse, basculez en mode « Proforma » puis validez : le document PDF est prêt.',
                'Envoyez-le par WhatsApp depuis la fiche du devis.',
                'Quand le client achète : « Transformer en vente » reprend les prix garantis.',
                'Un devis expiré se recrée au prix du jour en un clic.',
            ],
            'lien' => 'devis.index', 'permission' => 'ventes.voir'],

        'garantie' => ['rubrique' => 'caisse', 'titre' => 'Garantie et numéros de série (IMEI)',
            'mots' => 'garantie numéro de série imei téléphone appareil panne sav service après-vente fabrication',
            'resume' => 'Le numéro de chaque appareil vendu est noté et imprimé avec la date de fin de garantie ; on le retrouve en quelques secondes.',
            'etapes' => [
                'Fiche produit : indiquez la garantie en mois, et cochez « Noter le numéro de série » pour les appareils (téléphones, télévisions…).',
                'Après l\'encaissement, un bandeau rappelle les numéros à saisir : tapez-les ou scannez-les, puis « Enregistrer les numéros ».',
                'Le reçu et la facture affichent chaque numéro et la date de fin de garantie.',
                'Un client revient avec un appareil : Ventes → Garanties, tapez le numéro (les 6 derniers chiffres suffisent), son nom ou son téléphone.',
                'Un numéro déjà vendu est refusé : c\'est souvent une erreur de saisie ou un appareil déjà sorti.',
            ],
            'lien' => 'garanties.index', 'permission' => 'ventes.voir'],

        'livraison' => ['rubrique' => 'caisse', 'titre' => 'Livrer une vente chez le client',
            'mots' => 'livraison livrer livreur bon de livraison adresse domicile chantier transport réception signature',
            'resume' => 'Adresse, date, livreur, bon de livraison à faire signer, et suivi « à livrer / en route / livrée ».',
            'etapes' => [
                'Ouvrez la vente → bloc « Livraison » → « Livrer cette vente chez le client » : adresse (quartier, repère), contact sur place, date prévue.',
                'Imprimez le bon de livraison (sans les prix) : le livreur le fait signer et note les éventuelles réserves.',
                'Au départ, indiquez le nom du livreur ; « Prévenir le client » envoie un message WhatsApp.',
                'Si le client n\'a pas tout payé, le montant à encaisser est écrit en rouge sur le bon.',
                'Au retour, cliquez « Livrée » avec le nom de la personne qui a réceptionné.',
                'Menu Ventes → Livraisons : ce qui reste à livrer, les retards en rouge ; le tableau de bord rappelle les livraisons du jour.',
                'Une vente livrée ne s\'annule plus : pour reprendre des articles, faites un retour.',
            ],
            'lien' => 'livraisons.index', 'permission' => 'ventes.voir'],

        'acompte' => ['rubrique' => 'caisse', 'titre' => 'Encaisser un acompte sur une commande',
            'mots' => 'acompte avance commande réservation arrhes versement reste à payer livraison',
            'resume' => 'Le client verse une avance sur un devis ou une commande ; elle est déduite à la livraison.',
            'etapes' => [
                'Ouvrez le devis (ou la commande reçue sur la vitrine) → « Encaisser un acompte » : montant et moyen de paiement.',
                'Remettez le reçu d\'acompte au client (impression 80 mm ou envoi WhatsApp).',
                'L\'argent compte dans la caisse du jour du versement, pas à la livraison.',
                'À la livraison, « Transformer en vente » : l\'acompte est déduit, le client ne paie que le reste.',
                'Commande annulée : l\'acompte est remboursé au client, dans le moyen choisi.',
                'Devis expiré et recréé au prix du jour : l\'acompte passe sur le nouveau devis.',
            ],
            'lien' => 'devis.index', 'permission' => 'ventes.creer'],

        'retour' => ['rubrique' => 'caisse', 'titre' => 'Reprendre un article (retour, avoir)',
            'mots' => 'retour remboursement avoir défectueux échange reprise',
            'resume' => 'Retour partiel : le stock remonte, la caisse ou la dette du client est corrigée.',
            'etapes' => [
                'Ouvrez la vente dans l\'historique, bouton « Retour ».',
                'Indiquez les quantités rendues et le motif.',
                'Le montant à rembourser tient compte de la remise et de la TVA de chaque article.',
                'Sur une vente à crédit, la dette du client baisse au lieu d\'un remboursement.',
            ],
            'lien' => 'ventes.index', 'permission' => 'ventes.voir'],

        'ecran-client' => ['rubrique' => 'caisse', 'titre' => 'Afficher le ticket au client (écran client)',
            'mots' => 'écran client afficheur second écran tablette moniteur total monnaie transparence',
            'resume' => 'Le client voit ses articles, le total et sa monnaie sur un écran tourné vers lui.',
            'etapes' => [
                'À la caisse, bouton « Écran client » (icône d\'écran) : une nouvelle fenêtre s\'ouvre.',
                'Glissez-la sur le second écran ou la tablette tournée vers le client, puis « Plein écran ».',
                'Chaque article scanné s\'affiche aussitôt, avec la remise, la TVA, le total et la monnaie à rendre.',
                'À la validation, l\'écran remercie le client ; entre deux clients, il présente vos promotions en cours.',
                'Une fois ouvert, il continue de fonctionner même si Internet coupe ; la caisse et l\'écran doivent être ouverts dans le même navigateur (même ordinateur).',
            ],
            'lien' => 'ventes.create', 'permission' => 'ventes.creer'],

        'avoir' => ['rubrique' => 'caisse', 'titre' => 'Rendre un avoir au lieu de l\'argent',
            'mots' => 'avoir bon d achat retour échange crédit client remboursement reprise',
            'resume' => 'Le client rapporte un article : il repart avec un avoir à dépenser chez vous, l\'argent reste en caisse.',
            'etapes' => [
                'Ouvrez la vente, « Retour de marchandise », puis choisissez « Avoir client » comme remboursement.',
                'L\'avoir est nominatif : la vente doit être rattachée à un client. Son solde apparaît sur sa fiche.',
                'Imprimez le bon d\'avoir (bouton affiché après le retour) et remettez-le au client, ou envoyez-le par WhatsApp. Depuis sa fiche, « Bon de solde » réimprime le solde à jour.',
                'À son prochain passage, sélectionnez le client à la caisse : « Utiliser son avoir » est coché d\'office et réduit le montant à payer.',
                'Un achat payé en avoir, s\'il est retourné, redevient un avoir (jamais de l\'argent).',
                'Au rapport Z, les avoirs sont affichés à part et ne comptent pas dans l\'argent encaissé.',
            ],
            'lien' => 'ventes.index', 'permission' => 'ventes.voir'],

        'carte-cadeau' => ['rubrique' => 'caisse', 'titre' => 'Vendre et encaisser une carte cadeau',
            'mots' => 'carte cadeau bon d achat chèque cadeau offrir anniversaire fête cadeau prépayé code solde',
            'resume' => 'Un client paie une carte cadeau ; la personne qui la reçoit la dépense plus tard avec son code.',
            'etapes' => [
                'Ventes → Cartes cadeaux : valeur de la carte, moyen de paiement, date de validité (un an par défaut), et si vous voulez le nom de la personne à qui elle est offerte et un petit mot.',
                'Imprimez la carte (ticket 80 mm) ou envoyez-la par WhatsApp : le code CC-XXXX-XXXX qu\'elle porte suffit pour la dépenser, elle n\'est pas nominative.',
                'L\'argent entre dans la caisse le jour où la carte est vendue. Ce n\'est pas encore une vente : le chiffre d\'affaires est compté quand la carte est dépensée.',
                'À la caisse, « Payer avec une carte cadeau » : saisissez le code puis « Vérifier ». Le solde est déduit du total, le client paie le reste par un autre moyen.',
                'La carte se dépense en plusieurs fois, jamais au-delà de son solde ni après sa date de validité (un responsable peut la prolonger).',
                'Vente annulée ou article rapporté : ce qui avait été payé avec la carte retourne sur la carte.',
                'Carte perdue ou client remboursé : un responsable peut annuler la carte depuis sa fiche ; le solde restant est rendu et sort de la caisse.',
            ],
            'lien' => 'cartes-cadeaux.index', 'permission' => 'ventes.voir'],

        'hors-ligne' => ['rubrique' => 'caisse', 'titre' => 'Vendre sans connexion Internet',
            'mots' => 'hors ligne internet coupure connexion réseau synchronisation',
            'resume' => 'La caisse continue de fonctionner pendant une coupure et se synchronise au retour du réseau.',
            'etapes' => [
                'Ouvrez la caisse une fois avec Internet : le catalogue est gardé sur l\'appareil.',
                'Pendant la coupure, vendez normalement : un reçu provisoire est imprimé.',
                'Au retour d\'Internet, les ventes sont envoyées seules ; un bandeau indique celles en attente.',
            ],
            'lien' => 'ventes.create', 'fonction' => 'hors_ligne', 'permission' => 'ventes.creer'],

        'cloture' => ['rubrique' => 'caisse', 'titre' => 'Clôturer la caisse le soir (rapport Z)',
            'mots' => 'clôture fermeture caisse soir rapport z écart comptage billets fond',
            'resume' => 'Comptez l\'argent, comparez au théorique, justifiez l\'écart.',
            'etapes' => [
                'Clôtures de caisse → Nouvelle clôture.',
                'Ouvrez « Compter billet par billet » : indiquez le nombre de billets de 20 000, 10 000, 5 000… GNF ; le total se calcule tout seul (ou saisissez directement le montant compté).',
                'Le logiciel affiche l\'écart avec les espèces théoriques ; le détail des billets est imprimé sur le rapport Z.',
                'Un écart doit être expliqué ; la clôture est ensuite signée dans le registre.',
                'Le rapport Z s\'imprime avec son empreinte d\'intégrité.',
            ],
            'lien' => 'clotures.index', 'permission' => 'ventes.voir'],

        'reception' => ['rubrique' => 'stock', 'titre' => 'Recevoir une marchandise (approvisionnement)',
            'mots' => 'achat fournisseur réception arrivage livraison approvisionnement facture fournisseur',
            'resume' => 'Le stock augmente et le prix d\'achat se met à jour ; la dette fournisseur est suivie.',
            'etapes' => [
                'Approvisionnements → Nouveau.',
                'Choisissez le fournisseur, ajoutez les produits, quantités et prix payés.',
                'Indiquez ce qui a été payé : le reste devient une dette fournisseur avec échéance.',
                'Produits périssables : saisissez le lot et la date de péremption.',
            ],
            'lien' => 'approvisionnements.create', 'permission' => 'approvisionnements.gerer'],

        'retour-fournisseur' => ['rubrique' => 'stock', 'titre' => 'Renvoyer une marchandise au fournisseur',
            'mots' => 'retour fournisseur défectueux périmé erreur livraison avoir fournisseur remboursement bon de retour renvoyer',
            'resume' => 'Le produit sort du stock, et sa valeur est déduite de votre dette, remboursée ou gardée en avoir chez le fournisseur.',
            'etapes' => [
                'Approvisionnements → ouvrez la réception concernée → « Renvoyer de la marchandise au fournisseur ».',
                'Indiquez les quantités renvoyées (dans l\'unité reçue : pièce ou carton) et le motif : défectueux, périmé, erreur de livraison…',
                'La valeur, au prix d\'achat de cette réception, se déduit d\'abord de ce que vous devez encore.',
                'Si la réception était déjà payée, choisissez : le fournisseur vous rembourse (l\'argent rentre dans la caisse ou sur le compte choisi) ou vous accorde un avoir.',
                'Un avoir s\'utilise dans Dettes fournisseurs : moyen de règlement « Avoir fournisseur ».',
                'Imprimez le bon de retour et faites-le signer par le livreur ou le fournisseur.',
            ],
            'lien' => 'approvisionnements.index', 'permission' => 'approvisionnements.gerer'],

        'a-commander' => ['rubrique' => 'stock', 'titre' => 'Savoir quoi commander',
            'mots' => 'rupture commande réapprovisionnement seuil alerte couverture',
            'resume' => 'La liste calcule la quantité à commander selon vos ventes récentes.',
            'etapes' => [
                'Stock → À commander : produits sous le seuil ou qui ne tiendront pas la période de couverture.',
                'La quantité proposée se règle dans Paramètres → Règles de gestion (couverture en jours).',
                'Les produits dormants (qui ne se vendent plus) sont signalés à part.',
            ],
            'lien' => 'stock.a-commander', 'permission' => 'approvisionnements.gerer'],

        'commande-fournisseur' => ['rubrique' => 'stock', 'titre' => 'Passer et suivre une commande fournisseur',
            'mots' => 'commande fournisseur bon de commande reliquat livraison attendue réceptionner commandé en attente',
            'resume' => 'La commande est enregistrée, envoyée au fournisseur, puis réceptionnée en un clic ; rien n\'est commandé deux fois.',
            'etapes' => [
                'Stock → À commander : ajustez les quantités, la date de livraison souhaitée, puis « Enregistrer la commande ».',
                'Sur la commande : « Envoyer au fournisseur » (WhatsApp) ou imprimez le bon de commande.',
                'À l\'arrivée : « Réceptionner » ouvre la réception avec le fournisseur et les quantités restantes déjà remplis ; corrigez selon ce qui est vraiment arrivé.',
                'Livraison incomplète : la commande passe « Reçue en partie » et le reste attend la prochaine réception.',
                'Si le reste n\'arrivera jamais : « Le reste n\'arrivera pas : clore la commande ».',
                'Tant qu\'une commande est en attente, « À commander » en tient compte et ne la propose pas une deuxième fois.',
            ],
            'lien' => 'commandes-fournisseur.index', 'permission' => 'approvisionnements.gerer'],

        'inventaire' => ['rubrique' => 'stock', 'titre' => 'Faire un inventaire',
            'mots' => 'inventaire comptage écart perte vol casse ajustement',
            'resume' => 'Comptez le rayon, le logiciel corrige le stock et chiffre les écarts.',
            'etapes' => [
                'Stock → Inventaire, filtrez par catégorie pour compter rayon par rayon.',
                'Saisissez les quantités comptées ; les écarts sont valorisés au prix d\'achat.',
                'Validez : chaque correction est tracée dans les mouvements de stock.',
            ],
            'lien' => 'stock.inventaire', 'permission' => 'stock.ajuster'],

        'etiquettes' => ['rubrique' => 'stock', 'titre' => 'Imprimer étiquettes prix et codes-barres',
            'mots' => 'étiquette code barre impression prix rayon',
            'resume' => 'Planche d\'étiquettes avec nom, prix et code-barres, prête à coller.',
            'etapes' => ['Produits → Étiquettes : recherchez les produits ou filtrez par catégorie.',
                'Indiquez le nombre d\'étiquettes par produit (ou la quantité en stock), le format de planche, avec ou sans prix.',
                'Imprimez la planche et collez les étiquettes en rayon.'],
            'lien' => 'produits.etiquettes', 'fonction' => 'etiquettes', 'permission' => 'produits.voir'],

        'peremptions' => ['rubrique' => 'stock', 'titre' => 'Suivre les dates de péremption',
            'mots' => 'péremption date limite périmé lot DLC',
            'resume' => 'Les lots proches de la date limite sont signalés pour être vendus en priorité.',
            'etapes' => ['Saisissez la date à la réception.', 'Stock → Péremptions : lots périmés et à surveiller.',
                'Le délai d\'alerte se règle dans Paramètres.'],
            'lien' => 'stock.peremptions', 'fonction' => 'peremptions', 'permission' => 'produits.voir'],

        'credit' => ['rubrique' => 'clients', 'titre' => 'Vendre à crédit et relancer',
            'mots' => 'crédit dette ardoise plafond relance whatsapp paiement échéance',
            'resume' => 'Plafond, date de paiement promise et relance WhatsApp pour ne plus perdre d\'argent sur l\'ardoise.',
            'etapes' => [
                'La vente à crédit exige un client ; la caisse prévient si son plafond est dépassé ou s\'il est en retard.',
                'À la caisse, indiquez « Reste à payer avant le » : la date promise par le client (par défaut, le délai de crédit des Paramètres, 30 jours à défaut). Elle est imprimée sur le reçu et la facture.',
                'Crédits clients : qui doit combien et pour quand. Filtres « En retard » et « Échéance dans 7 jours » pour savoir qui appeler.',
                'Le client demande un délai ? Ouvrez la vente → « Reporter l\'échéance ».',
                'Si un délai de crédit est réglé dans Paramètres, un client en retard ne peut plus prendre à crédit (il peut toujours payer comptant).',
                'Bouton WhatsApp : message de relance prérempli avec le montant et la date de paiement convenue.',
                'Encaissez un règlement depuis la fiche client ; le relevé de compte se télécharge en PDF.',
            ],
            'lien' => 'credits.index', 'permission' => 'ventes.voir'],

        'doublons' => ['rubrique' => 'clients', 'titre' => 'Fusionner les fiches clients en double',
            'mots' => 'doublon double fusion fusionner fiche client même client recréé regrouper',
            'resume' => 'Un client enregistré deux fois : regroupez ses achats, crédits, points et avoirs sur une seule fiche.',
            'etapes' => [
                'Clients → Doublons : les fiches au même nom ou au même téléphone sont regroupées.',
                'Pour chaque groupe, choisissez la fiche à garder (la plus ancienne par défaut) et cochez celles à fusionner.',
                'Ventes, crédits, paiements, devis, points de fidélité, avoirs et cartes cadeaux passent sur la fiche gardée ; les coordonnées manquantes sont complétées.',
                'La fusion est inscrite au registre anti-fraude : le contrôle d\'intégrité reste « intact ». Réservé à l\'administrateur, car les dettes changent de fiche.',
            ],
            'lien' => 'clients.doublons', 'permission' => 'parametres.gerer'],

        'clients-inactifs' => ['rubrique' => 'clients', 'titre' => 'Faire revenir les clients qui n\'achètent plus',
            'mots' => 'relance client inactif perdu revenir fidéliser marketing whatsapp segment fidèle nouveau',
            'resume' => 'La liste « À relancer » et une invitation WhatsApp avec vos promotions du moment.',
            'etapes' => [
                'Clients → « À relancer » : ceux qui ont déjà acheté mais ne sont pas revenus depuis 30, 60, 90 ou 180 jours.',
                'Bouton « Inviter » : WhatsApp s\'ouvre avec un message prêt, qui cite vos promotions en cours et votre vitrine en ligne.',
                'Un client invité sort de la liste pendant 14 jours : on ne le sollicite pas deux fois de suite.',
                'Les autres filtres repèrent vos clients fidèles (3 achats en 90 jours), les nouveaux et ceux qui doivent de l\'argent.',
            ],
            'lien' => 'clients.index', 'fonction' => 'relances', 'permission' => 'clients.voir'],

        'anniversaires' => ['rubrique' => 'clients', 'titre' => 'Souhaiter l\'anniversaire de ses clients',
            'mots' => 'anniversaire naissance fête cadeau vœux whatsapp fidéliser client',
            'resume' => 'Un message WhatsApp le jour J, avec le cadeau que vous choisissez : le client s\'en souvient.',
            'etapes' => [
                'Fiche client → Date de naissance (facultative).',
                'Paramètres → Règles de gestion : « Cadeau d\'anniversaire » (ex. : -10 % sur votre achat cette semaine). Vide = simple vœu.',
                'Le jour J, le tableau de bord vous prévient ; Clients → « Anniversaires (7 jours) » liste ceux de la semaine avec le bouton « Souhaiter ».',
                'Un seul message par client et par an. À la caisse, le vendeur voit « C\'est son anniversaire aujourd\'hui ! » quand il sélectionne le client.',
            ],
            'lien' => 'clients.index', 'fonction' => 'relances', 'permission' => 'clients.voir'],

        'fidelite' => ['rubrique' => 'clients', 'titre' => 'Programme de fidélité',
            'mots' => 'fidélité points récompense client régulier',
            'resume' => 'Les clients cumulent des points sur leurs achats payés et les utilisent en réduction.',
            'etapes' => ['Paramètres : pourcentage de points gagnés et seuil minimal d\'utilisation.',
                'À la caisse, les points du client s\'affichent et peuvent être utilisés.'],
            'lien' => 'parametres.edit', 'fonction' => 'fidelite', 'permission' => 'parametres.gerer'],

        'promotions' => ['rubrique' => 'clients', 'titre' => 'Lancer une promotion',
            'mots' => 'promotion solde réduction prix barré période',
            'resume' => 'Prix réduit sur une période : appliqué seul à la caisse et sur la vitrine.',
            'etapes' => ['Stock → Promotions → Nouvelle.', 'Choisissez les produits, le prix ou le pourcentage, les dates.',
                'À la fin de la période, le prix normal revient automatiquement.'],
            'lien' => 'promotions.index', 'fonction' => 'promotions', 'permission' => 'produits.gerer'],

        'depenses' => ['rubrique' => 'argent', 'titre' => 'Noter les dépenses et sorties de caisse',
            'mots' => 'dépense loyer électricité transport salaire sortie caisse',
            'resume' => 'Chaque sortie d\'argent est notée pour un bénéfice net juste.',
            'etapes' => ['Dépenses → Nouvelle : montant, catégorie, mode de paiement.',
                'Une dépense payée en espèces diminue la caisse attendue à la clôture.'],
            'lien' => 'depenses.index', 'permission' => 'depenses.gerer'],

        'tva' => ['rubrique' => 'argent', 'titre' => 'TVA : taux normal et produits exonérés',
            'mots' => 'tva taxe exonéré taux 18 impôt déclaration fiscal',
            'resume' => 'Taux de la boutique par défaut, taux propre à un produit si besoin (0 % = exonéré).',
            'etapes' => [
                'Paramètres → TVA : activez-la et indiquez le taux normal (18 % en Guinée). Le réglage ne vaut que pour cette boutique : chaque point de vente d\'un réseau a le sien.',
                'Deux façons de saisir vos prix. Par défaut, hors taxe : la TVA s\'y ajoute à la caisse (avec 18 %, un article à 10 000 GNF est encaissé 11 800 GNF).',
                'Si vos étiquettes affichent déjà le prix payé par le client, cochez « Mes prix de vente sont TVA comprise (TTC) » : le client paie exactement le prix affiché et la TVA en est extraite (10 000 GNF encaissés, dont 1 525 GNF de TVA). Les ventes déjà faites ne changent pas.',
                'Fiche produit → Régime de TVA : « Taux normal », « Exonéré » ou un autre taux. Le prix payé par le client (TTC) s\'affiche sous le prix de vente.',
                'Les reçus et factures détaillent la TVA par taux ; le rapport TVA sert à la déclaration.',
            ],
            'lien' => 'parametres.edit', 'permission' => 'parametres.gerer'],

        'rapports' => ['rubrique' => 'argent', 'titre' => 'Lire ses chiffres (rapports et analyse)',
            'mots' => 'rapport chiffre affaires bénéfice marge analyse comparaison heures pointe',
            'resume' => 'Chiffre d\'affaires, marge, meilleurs produits, comparaison avec la période précédente.',
            'etapes' => ['Rapports : choisissez la période ; exportez en Excel ou PDF.',
                'Analyse : évolution par rapport à la période précédente et à l\'an dernier, heures de pointe, rentabilité.',
                'Export comptable SYSCOHADA pour votre comptable.'],
            'lien' => 'rapports.index', 'permission' => 'rapports.voir'],

        'tresorerie' => ['rubrique' => 'argent', 'titre' => 'Suivre la trésorerie (caisse, mobile money, banque)',
            'mots' => 'trésorerie banque orange money compte solde versement',
            'resume' => 'Le solde de chaque compte, les versements et les transferts entre comptes.',
            'etapes' => ['Trésorerie : un compte par caisse, portefeuille mobile money et banque.',
                'Enregistrez les apports, retraits et transferts (dépôt des espèces à la banque, frais inclus).',
                'Faites régulièrement un « constat de solde » : le logiciel signale l\'écart avec le solde théorique.'],
            'lien' => 'tresorerie.index', 'fonction' => 'tresorerie', 'permission' => 'tresorerie.gerer'],

        'utilisateurs' => ['rubrique' => 'equipe', 'titre' => 'Créer les comptes des vendeurs et leurs droits',
            'mots' => 'utilisateur vendeur caissier gérant rôle droit permission accès',
            'resume' => 'Chacun ne voit que ce qu\'il doit voir : un vendeur n\'accède pas aux marges.',
            'etapes' => ['Utilisateurs → Nouveau : nom, identifiant, rôle.',
                'Rôles et droits : cochez ce que chaque rôle peut faire (remise, annulation, prix d\'achat…).',
                'Un compte désactivé ne peut plus se connecter, son historique reste.'],
            'lien' => 'utilisateurs.index', 'permission' => 'utilisateurs.gerer'],

        'pointage' => ['rubrique' => 'equipe', 'titre' => 'Pointage et planning de l\'équipe',
            'mots' => 'pointage présence retard absence planning horaire équipe',
            'resume' => 'Arrivées et départs, retards, heures travaillées, planning de la semaine.',
            'etapes' => ['Chaque vendeur pointe son arrivée et son départ depuis le bandeau du haut.',
                'Équipe → Planning : placez les horaires ; les heures d\'affluence guident les besoins.',
                'Les retards et absences sont calculés par rapport au planning.'],
            'lien' => 'equipe.index', 'fonction' => 'equipe', 'permission' => 'utilisateurs.gerer'],

        'objectifs' => ['rubrique' => 'equipe', 'titre' => 'Objectifs de vente et commissions',
            'mots' => 'objectif chiffre affaires mois vendeur commission prime classement motivation équipe',
            'resume' => 'Un objectif pour la boutique et pour chaque vendeur, suivis en direct ; commissions calculées toutes seules.',
            'etapes' => [
                'Paramètres → Règles de gestion : objectif de ventes du mois de la boutique.',
                'Utilisateurs → modifier un vendeur : son objectif du mois et sa commission (% des ventes hors taxes).',
                'Tableau de bord : progression, projection de fin de mois et montant à vendre chaque jour pour tenir l\'objectif.',
                'Le classement de l\'équipe montre les ventes de chacun et le total des commissions à verser.',
                'À la caisse, chaque vendeur voit sa propre progression du mois.',
                'Équipe → Commissions : une fois le mois terminé, « Verser » enregistre le paiement (espèces, Orange Money…) et crée la dépense « Salaires ».',
                'Le montant versé est figé ; l\'historique des 12 derniers mois et l\'export Excel ou PDF servent à la paie.',
            ],
            'lien' => 'utilisateurs.index', 'fonction' => 'equipe', 'permission' => 'utilisateurs.gerer'],

        'integrite' => ['rubrique' => 'equipe', 'titre' => 'Registre anti-fraude et intégrité',
            'mots' => 'fraude sécurité registre intégrité empreinte modification suppression contrôle',
            'resume' => 'Chaque vente, annulation et clôture est signée : toute modification est détectée.',
            'etapes' => ['Rapports → Intégrité : vérification complète du registre.',
                'Les reçus et rapports Z portent une empreinte qui prouve qu\'ils n\'ont pas été modifiés.',
                'Une archive signée est produite chaque mois ; téléchargez-la pour un contrôle.'],
            'lien' => 'integrite.index', 'permission' => 'rapports.voir'],

        'vitrine' => ['rubrique' => 'vente_en_ligne', 'titre' => 'Ouvrir sa vitrine en ligne',
            'mots' => 'vitrine en ligne site internet catalogue whatsapp facebook commande à distance',
            'resume' => 'Une page publique avec vos produits et prix ; les clients commandent depuis leur téléphone.',
            'etapes' => [
                'Paramètres → Vitrine en ligne : cochez « Publier ma vitrine ».',
                'Copiez l\'adresse ou partagez-la sur WhatsApp, Facebook, dans votre statut.',
                'Chaque commande arrive dans Devis / proforma avec le badge « Vitrine » et une notification.',
                'Appelez le client pour confirmer, puis « Transformer en vente » : le stock baisse seulement à ce moment.',
                'Pour retirer un produit de la vitrine : fiche produit → décochez « Visible sur la vitrine ».',
            ],
            'lien' => 'parametres.edit', 'fonction' => 'vitrine', 'permission' => 'parametres.gerer'],
    ],
];
